In [1]:
import numpy as np
arr = np.arange(10) * 10
arr

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [4]:
#索引
arr[1]

#slice切割
arr[:5] #取前5個
arr[-5:] #取後5個

array([50, 60, 70, 80, 90])

In [6]:
scores = np.random.randint(50,101,size = (50,5))
scores

array([[ 62,  54,  55,  78,  95],
       [ 54,  71, 100,  96,  50],
       [ 56,  97,  73,  85,  55],
       [ 61,  95,  73,  90,  70],
       [ 95,  94,  94,  73,  79],
       [ 69,  58,  88,  80,  72],
       [ 85, 100, 100,  65,  97],
       [ 83,  85,  84,  70,  57],
       [ 90,  71,  64,  92,  96],
       [ 68,  73,  66,  61,  59],
       [ 68,  84,  80,  61,  52],
       [ 69,  65,  64,  63,  50],
       [ 93,  88,  64,  67,  51],
       [ 92,  89,  69,  72,  83],
       [ 61,  80,  64,  98, 100],
       [ 94,  88,  79,  79,  77],
       [ 97,  66,  53,  96,  92],
       [ 58,  87,  75,  77,  87],
       [ 91,  61,  82,  77,  58],
       [ 97,  55,  98,  85,  74],
       [ 96,  78,  64,  93,  91],
       [ 86,  82,  78,  65,  93],
       [ 88,  80,  62,  92,  89],
       [ 87,  75,  58,  97,  58],
       [ 69,  93,  52,  97,  88],
       [ 60,  90,  72,  97,  60],
       [ 55,  60,  74,  57,  88],
       [ 71,  77,  66,  63,  74],
       [ 88,  96,  93,  75,  70],
       [ 84,  

In [7]:
#第一位學生的分數
scores[0] #(5,)
scores[0,:] #(5,)
scores[0:1,:] #(1, 5)

array([[62, 54, 55, 78, 95]], dtype=int32)

In [8]:
#前5位學生
scores[:5]
#前5位學生,前3個分數
scores[:5,:3]

array([[ 62,  54,  55],
       [ 54,  71, 100],
       [ 56,  97,  73],
       [ 61,  95,  73],
       [ 95,  94,  94]], dtype=int32)

In [14]:
#第1科分數
scores[:,0]
scores[:,1]
scores[:,2]

array([ 55, 100,  73,  73,  94,  88, 100,  84,  64,  66,  80,  64,  64,
        69,  64,  79,  53,  75,  82,  98,  64,  78,  62,  58,  52,  72,
        74,  66,  93,  90,  69,  60,  80,  54,  74, 100,  67,  59,  67,
        60,  64,  82,  63,  94,  94,  51,  89,  97,  98,  54], dtype=int32)

In [10]:
#ndarray可以陣列運算
total = scores[:,0] + scores[:,1] + scores[:,2] + scores[:,3] + scores[:,4]
total

array([344, 371, 366, 389, 435, 367, 447, 379, 413, 327, 345, 311, 363,
       405, 403, 417, 404, 384, 369, 409, 422, 404, 411, 375, 399, 379,
       334, 351, 422, 403, 343, 351, 388, 298, 410, 460, 347, 340, 387,
       339, 330, 417, 338, 397, 400, 382, 371, 381, 434, 373], dtype=int32)

In [11]:
total / 5

array([68.8, 74.2, 73.2, 77.8, 87. , 73.4, 89.4, 75.8, 82.6, 65.4, 69. ,
       62.2, 72.6, 81. , 80.6, 83.4, 80.8, 76.8, 73.8, 81.8, 84.4, 80.8,
       82.2, 75. , 79.8, 75.8, 66.8, 70.2, 84.4, 80.6, 68.6, 70.2, 77.6,
       59.6, 82. , 92. , 69.4, 68. , 77.4, 67.8, 66. , 83.4, 67.6, 79.4,
       80. , 76.4, 74.2, 76.2, 86.8, 74.6])

In [17]:
#np內的function
np.sum(scores,axis=1)
np.mean(scores,axis=1)

array([68.8, 74.2, 73.2, 77.8, 87. , 73.4, 89.4, 75.8, 82.6, 65.4, 69. ,
       62.2, 72.6, 81. , 80.6, 83.4, 80.8, 76.8, 73.8, 81.8, 84.4, 80.8,
       82.2, 75. , 79.8, 75.8, 66.8, 70.2, 84.4, 80.6, 68.6, 70.2, 77.6,
       59.6, 82. , 92. , 69.4, 68. , 77.4, 67.8, 66. , 83.4, 67.6, 79.4,
       80. , 76.4, 74.2, 76.2, 86.8, 74.6])

In [19]:
#實體方法
scores.sum(axis=1)
scores.mean(axis=1)

array([68.8, 74.2, 73.2, 77.8, 87. , 73.4, 89.4, 75.8, 82.6, 65.4, 69. ,
       62.2, 72.6, 81. , 80.6, 83.4, 80.8, 76.8, 73.8, 81.8, 84.4, 80.8,
       82.2, 75. , 79.8, 75.8, 66.8, 70.2, 84.4, 80.6, 68.6, 70.2, 77.6,
       59.6, 82. , 92. , 69.4, 68. , 77.4, 67.8, 66. , 83.4, 67.6, 79.4,
       80. , 76.4, 74.2, 76.2, 86.8, 74.6])