In [1]:
import numpy as np
#陣列運算
a = np.array([1,3,5,7,9])
a *= 10
a

array([10, 30, 50, 70, 90])

In [2]:
a = np.array([1,3,5,7,9])
b = np.array([2,4,6,8,10])
#陣列運算
a + b

array([ 3,  7, 11, 15, 19])

In [ ]:
#2維的ndarry
arr = np.array([[1,3,5],[2,4,6]])
arr.ndim #維度
arr.shape #形狀
arr.size #元素數量
arr.dtype #型別

dtype('int64')

In [14]:
np.random.rand()
np.random.rand(10,4)

array([[0.44410593, 0.06410805, 0.57110656, 0.95747051],
       [0.85849891, 0.45426766, 0.49705669, 0.64684912],
       [0.9038972 , 0.33760529, 0.22354018, 0.35007556],
       [0.24793469, 0.87147932, 0.74803658, 0.75358665],
       [0.56344144, 0.46554011, 0.75478774, 0.09128791],
       [0.02883353, 0.96908599, 0.37515032, 0.86995035],
       [0.89563401, 0.37726231, 0.80066548, 0.17436918],
       [0.88884988, 0.02775521, 0.81723884, 0.83500485],
       [0.49176041, 0.0090164 , 0.69997184, 0.59770291],
       [0.26056635, 0.15740225, 0.78140347, 0.12933587]])

In [13]:
scores = np.random.randint(50, 101,size=(30,5))
scores

array([[ 53,  99,  59,  60,  97],
       [ 56,  89,  63,  90,  74],
       [ 69,  86,  51,  81,  50],
       [ 70,  84,  62,  79,  77],
       [ 99,  58,  74,  50,  81],
       [ 73,  66,  62,  95,  60],
       [ 96,  53,  90,  96,  92],
       [ 89,  64,  51,  60,  52],
       [ 59,  82,  95,  92,  96],
       [ 85,  78,  53,  74,  75],
       [ 54,  99,  76,  88, 100],
       [ 81,  56,  56,  90,  84],
       [ 94,  80,  70,  53,  97],
       [ 72,  98,  80,  88,  77],
       [ 73,  88,  50,  54,  90],
       [ 73,  54,  76,  50,  61],
       [ 58,  67,  51,  78,  59],
       [ 80,  90,  88,  52,  88],
       [ 80,  71,  84,  77,  82],
       [ 63,  90,  66,  94,  98],
       [ 75,  90,  85,  60,  61],
       [ 62,  58,  56,  58,  60],
       [ 69,  80,  75,  67,  66],
       [ 97,  85, 100,  57,  56],
       [ 75,  70,  89,  50,  62],
       [ 81,  93,  66,  81,  51],
       [ 67,  58,  65,  92,  79],
       [100,  96,  89,  50,  51],
       [ 82,  53,  82,  61,  68],
       [ 70,  