In [ ]:
import numpy.random as ra1
money=[100,200,500,1000,5000,10000]
print('已經抽出五個桌號，接著抽出每一桌的三個獎項')
for a in range(5): #range(5)代表重複5次
  np1=ra1.choice(money,3) #在money這個list內挑選3個資料
  print(np1)

已經抽出五個桌號，接著抽出每一桌的三個獎項
[ 5000  1000 10000]
[5000  200 5000]
[5000 5000  200]
[  500 10000   200]
[200 200 500]


In [3]:
print('已經抽出五個桌號，接著抽出每一桌的三個獎項,可以做一些限制')
for a in range(5):
  np1=ra1.choice(money,3,p=[0.3,0.3,0.2,0.1,0.1,0])
  # 在money這個list內挑選3個資料，這三個資料會有不同的比例抓取，money內有六種可能
  # 第一種可能是30% 第二種30% 第三種20% 第四種10% 第五種10% 第六種0%
  # p這個參數內的數量必須與money內的數量相同，比例加起來必須為1
  print(np1)

已經抽出五個桌號，接著抽出每一桌的三個獎項,可以做一些限制
[100 100 200]
[200 200 500]
[ 100  200 1000]
[500 500 500]
[ 500 1000 5000]


In [4]:
print('已經抽出五個桌號，接著抽出每一桌的三個獎項,可以做一些限制，另外希望不重複')
for a in range(5):
  np1=ra1.choice(money,3,p=[0.3,0.3,0.2,0.1,0.1,0],replace=False)
  # 在money這個list內挑選3個資料，這三個資料會有不同的比例抓取，money內有六種可能
  # 第一種可能是30% 第二種30% 第三種20% 第四種10% 第五種10% 第六種0%
  # p這個參數內的數量必須與money內的數量相同，比例加起來必須為1
  # 項目不重覆
  print(np1)

已經抽出五個桌號，接著抽出每一桌的三個獎項,可以做一些限制，另外希望不重複
[ 100  200 5000]
[5000  200  100]
[ 200 5000 1000]
[ 200 5000  500]
[ 200  500 5000]
